[tox]
envlist =
    ruff-check,
    py{38,39}-Plone52,
    py{310,311}-Plone60,
    py{310,311,312,313}-Plone61,

skip_missing_interpreters = True


[testenv]
skip_install = true

extras =
    develop
    test

commands =
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} bootstrap
    {envbindir}/buildout -n -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir}
    {envbindir}/pip install pytest pytest-plone>=0.5.0 pytest-cov
    coverage run {envbindir}/pytest {toxinidir}/tests -v {posargs}

setenv =
    COVERAGE_FILE=.coverage.{envname}
    Plone52: version_file=test_plone52.cfg
    Plone60: version_file=test_plone60.cfg
    Plone61: version_file=test_plone61.cfg

deps =
    Plone52: -rrequirements_plone52.txt
    Plone60: -rrequirements_plone60.txt
    Plone61: -rrequirements_plone61.txt
    coverage


[testenv:ruff-check]
basepython = python3.11
skip_install = True
deps =
    -cconstraints_plone61.txt
    ruff

commands =
    ruff check src tests
    ruff format --check --diff src tests


[testenv:ruff-fix]
basepython = python3.11
skip_install = True
deps =
    -cconstraints_plone61.txt
    ruff

commands =
    ruff check --fix src tests
    ruff format src tests


[testenv:coverage-report]
skip_install = true
basepython = python3.11

deps =
    coverage
    -cconstraints_plone61.txt

setenv =
    COVERAGE_FILE=.coverage

commands =
    coverage erase
    coverage combine
    coverage html
    coverage xml
    coverage report
