[tox]
envlist =
    ruff-check,
    py38-Plone52,
    py{310,311}-Plone60,
    py{310,311,312,313}-Plone61,

skip_missing_interpreters = True


[testenv]
skip_install = true

extras =
    develop
    test

commands =
    ; 1. Verify buildout compatibility
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} bootstrap
    {envbindir}/buildout -n -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} install test
    ; 2. Install package with test deps via pip (constrained to Plone version)
    {envbindir}/pip install -c {toxinidir}/{env:constraints_file} -e "{toxinidir}[test]"
    ; 3. Run pytest
    coverage run {envbindir}/pytest {toxinidir}/tests -v {posargs}

setenv =
    COVERAGE_FILE=.coverage.{envname}
    Plone52: version_file=test_plone52.cfg
    Plone52: constraints_file=constraints_plone52.txt
    Plone60: version_file=test_plone60.cfg
    Plone60: constraints_file=constraints_plone60.txt
    Plone61: version_file=test_plone61.cfg
    Plone61: constraints_file=constraints_plone61.txt

deps =
    Plone52: -rrequirements_plone52.txt
    Plone60: -rrequirements_plone60.txt
    Plone61: -rrequirements_plone61.txt
    coverage[toml]


[testenv:ruff-check]
basepython = python3.11
skip_install = True
deps =
    -cconstraints_plone61.txt
    ruff

commands =
    ruff check src tests
    ruff format --check --diff src tests


[testenv:ruff-fix]
basepython = python3.11
skip_install = True
deps =
    -cconstraints_plone61.txt
    ruff

commands =
    ruff check --fix src tests
    ruff format src tests


[testenv:coverage-report]
skip_install = true
basepython = python3.11

deps =
    coverage[toml]
    -cconstraints_plone61.txt

setenv =
    COVERAGE_FILE=.coverage

commands =
    coverage erase
    coverage combine
    coverage html
    coverage xml
    coverage report
